___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [4]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ivan Seredenko/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Ivan Seredenko/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ivan Seredenko/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_librarie

Створити вектор з 10 елементів, заповнений одиницями:

In [5]:
vect = np.ones(10)
vect

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [7]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [8]:
arr1 = np.zeros((5, 5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [22]:
arr2 = np.random.randint(0, 11, 20) #Задаем вектор из 20-ти элементов со случайными целыми числами с отрезка [0, 10]
print(arr2)
print(np.nonzero(arr2)) #Индексы ненулевых элементов

[ 7  9  9  0  8  3 10  5  7  4  1  0  0  2  6  0  9  2  2  3]
(array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 13, 14, 16, 17, 18, 19],
      dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [26]:
avg = np.mean(arr2)
md = np.median(arr2)
sd = np.std(arr2)
print(f'''Среднее - {avg}
Медиана - {md}
Стандартное отклонение - {sd}''')

Среднее - 4.35
Медиана - 3.5
Стандартное отклонение - 3.4245437652335533


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [369]:
m1 = np.random.randint(0, 11, (4, 2)) #Матрица 4х2 случайных чисел из отрезка [0, 10]
m2 = np.random.randint(0, 11, (2, 2)) #Матрица 2х2 случайных чисел из отрезка [0, 10]
print('Матрица 4х2:')
print(m1)
print('Матрица 2х2:')
print(m2)
M = np.dot(m1, m2) #Матричное произведение
print('Матричное произведение:')
print(M)

Матрица 4х2:
[[2 9]
 [9 5]
 [5 9]
 [8 9]]
Матрица 2х2:
[[5 1]
 [9 3]]
Матричное произведение:
[[ 91  29]
 [ 90  24]
 [106  32]
 [121  35]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [372]:
M1 = M.copy()
M1 = M1.flatten() #Переводим матрицу М в вектор
print(M1)

k1 = np.min(M1) #Минимальное значение
k2 = np.max(M1) #Максимальное значение
print(f'''Минимальное значение - {k1}
Максимальное значение - {k2}''')

k3 = np.argwhere(M1 == k2) #Индекс(ы) найбольшего(их) элемента(ов)
M1[k3] = 0 #Приравниваем максимальный элемент к 0
print(M1)

[ 91  29  90  24 106  32 121  35]
Минимальное значение - 24
Максимальное значение - 121
[ 91  29  90  24 106  32   0  35]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [371]:
r1 = M[0] #Первая строка
s = 0
for i in M[1:]:
    r2 = i
    s += 1
    corr = np.corrcoef(r1, r2)[0][1]
    print(f'Коэффициент корееляции с {s + 1}-ой строкой равен {corr}')

Коэффициент корееляции с 2-ой строкой равен 1.0
Коэффициент корееляции с 3-ой строкой равен 1.0
Коэффициент корееляции с 4-ой строкой равен 1.0


Дано матрицю. Знайти ранг матриці:

In [4]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
print('Ранг матрицы -', np.linalg.matrix_rank(a))

Ранг матрицы - 3


Знайти визначник матриці:

In [11]:
print('Определитель матрицы -', int(np.linalg.det(a)))

Определитель матрицы - 440


Знайти власні значення та власні вектори матриці: 

In [11]:
print('Собственные значения матрицы: ', np.linalg.eigh(a)[0])
print(f'''Собственные вектора матрицы: 
{np.linalg.eigh(a)[1]}''')

Собственные значения матрицы:  [-14.30540864  -4.34740072  23.65280936]
Собственные вектора матрицы: 
[[ 0.15315575  0.88160309  0.44645191]
 [ 0.63674998 -0.43353159  0.6376518 ]
 [-0.75570681 -0.18661821  0.62775861]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [26]:
a = np.random.randint(0,10,50)

def mode(x):
    val, counts = np.unique(x, return_counts=True)
    return val[np.argmax(counts)]

print(f'''Заданный массив:
{a}''')
print('Медиана: ', mode(a))

Заданный массив:
[2 6 5 7 1 7 7 0 7 2 2 9 4 0 9 4 5 2 0 0 5 3 5 8 0 2 1 3 9 5 8 4 3 3 2 1 8
 2 3 1 9 7 8 9 8 9 3 1 1 1]
Медиана:  1


Виведіть лише парні числа, що діляться на 5:

In [43]:
a = np.random.randint(0,10,50)
a[(a % 2 == 0) & (a % 5 == 0)]

array([0, 0, 0, 0, 0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [52]:
coef1 = np.array([[2, 5], [1, -10]]) #Левые части
coef2 = np.array([1, 3]) #Правые части
print(f'x1 = {np.linalg.solve(coef1, coef2)[0]}, x2 = {np.linalg.solve(coef1, coef2)[1]}')

x1 = 1.0, x2 = -0.2
